\" <rali - rust arch linux installer>
\" copyright (c) <2021>  <Jacob Stannix>

\" this program is free software: you can redistribute it and/or modify
\" it under the terms of the gnu general public license as published by
\" the free software foundation, either version 3 of the license, or
\" (at your option) any later version.

\" this program is distributed in the hope that it will be useful,
\" but without any warranty; without even the implied warranty of
\" merchantability or fitness for a particular purpose.  see the
\" gnu general public license for more details.

\" you should have received a copy of the gnu general public license
\" along with this program.  if not, see <https://www.gnu.org/licenses/>.
.TH "RALI.CONF" "5" "2021-05-20" "GNU" "RALI.0.1.0" 
.SH "NAME"
.PP
(Rust) Arch Linux Installer Configuration Guide
.SH "Description"
.PP
This man page descripts the process for writing a confgiuration file for rali. This file aims to ensure a consistant installaltion experiance accross arch machines or just between reinstalaitons.
.SH "System Configuration Options"
.PP
\fB[rali]\fP
.br
Configure instalation options. Command line swithces override the options set in this file.
.PP
.PP
\fB[pacman.conf]\fP
.br
Allows you to customise of your pacman.conf file.
.PP
.PP
\fB[pacman-mirrors]\fP
.br
Sets your mirror list in /etc/pacman.d/mirrorlist.
.PP
.PP
\fB[encription]\fP
.br
Set encription options
