.TH "RALI.CONF" "5" "2021-05-20" "GNU/Linux" "RALI.0.1.0" 
.SH "NAME"
.PP
(Rust) Arch Linux Installer Configuration Guide
.SH "Description"
.PP
This man page descripts the process for writing a confgiuration file for rali. This file aims to ensure a consistant installaltion experiance accross arch machines or just between reinstalaitons.
.SH "System Configuration Options"
.SS "[rali]"
.PP
Configure instalation options. Command line switches override the options set in this file.
.PP
.PP
\fBuefi\fP = \fI"[true/false]"\fP
sets whether or not rali configures the system for uefi or not.
.SS "[pacman.conf]"
.PP
Allows you to customise of your pacman.conf file.
.SS "[pacman-mirrors]"
.PP
Sets your mirror list in /etc/pacman.d/mirrorlist.
.SS "[encription]"
.PP
Set encription options
