.TH "RALI.CONF" "1" "2021-05-18" "GNU" "RALI.0.1.0" 
.SH "NAME"
.PP
(Rust) Arch Linux Installer Configuration Guide
.SH "Description"
.PP
This man page descripts the process for writing a confgiuration file for rali. This file aims to ensure a consistant installaltion experiance accross arch machines or just between reinstalaitons.
.SH "System Configuration Options"
.PP
\fB[rali]\fP
.br
Configure instalation options. Command line swithces override the options set in this file.
.PP
.PP
\fB[pacman.conf]\fP
.br
Allows you to customise of your pacman.conf file.
.PP
.PP
\fB[pacman-mirrors]\fP
.br
Sets your mirror list in /etc/pacman.d/mirrorlist.
.PP
.PP
\fB[encription]\fP
.br
Set encription options
