[package]
name = "rali" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Jacob Stannix <jakestannix @ gmail . com>"]
description = "An Arch Linux installer and reference."
repository = "https://github.com/delta1024/Rali"

[dependencies]