.TH "RALI" "1" "2021-05-25" "GNU/Linux" "RALI.0.1.0" 
.SH "NAME"
.PP
(Rust) Arch Linux Installer
.SH "SYNOPSIS"
.nf
.PP
rali
rali --PACKAGE\d\s-2LIST\s+2\u="package\d\s-2lists.txt\s+2\u"
.fi
.SH "DESCRIPTION"
.PP
rali is a cli Arch Linux configuration tool written in rust.
It aims to make installing Arch Linux as painless as possible;
any of the options other than the basic install require some knowledge of how to install and configure an Arch system.
See rali.conf(5) for more details
.SH "OPTIONS"
.PP
\fB--PACKAGE\d\s-2LIST\s+2\u=\fP​\fI<file>\fP​
.br
Replaces the default package list with a user specified one.

.PP
.PP
\fB--UEFI=\fP​\fIy,/n\fP
.br
If set to y configures your system for UEFI. For BIOS set to n. If left blank you will be prompted by the program.
.PP
.PP
\fB--basic, -b\fP 
.br
Installs the most basic Arch Linux system. No user, man pages, or info pages; just the bootloader, base, the kernel, and vim.
.SS "Exit Codes"
.PP
(4) wrong boot mode; user chose to exit program.
